### ISSUE TITLE
Authorization problem with ZDF API

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp-backend#1]
Since yesterday a 403 status code is returned. Most likely they changed their auth code. Maybe the error can be fixed by reverse engineering the apps or digging into the websites API calls.

**Comment by Medusalix** [comment]
I'd like to work on this issue.

**Comment by Medusalix** [comment]
Looks like the bearer token has change from `d2726b6c8c655e42b68b0db26131b15b22bd1a32` to `69c4eddbe0cf82b2a9277e8106a711db314a3008`. I get a valid response from the API endpoint now:

`{"shows":[{"title":"Rosamunde Pilcher: Sommer der Liebe","subtitle":null,"description":"Auf der Suche nach einem Job macht Elisabeth in der kleinen Gemeinde St. Annes zufällig die Bekanntschaft von Gregory. Noch ahnt sie nicht, dass sich ihr Leben bald vollkommen ändern wird.<br/><br/>Gregory verhilft ihr zu einem Job und beginnt schnell, sich in die bezaubernde junge Frau zu verlieben. Auch Elisabeth fühlt sich in seiner Nähe sehr wohl, doch sie hat ein merkwürdiges Gefühl: Sie glaubt, in ihrer Kindheit bereits in St. Annes gewesen zu sein.<br/><br/>Doch ihre Mutter, mit der sie telefoniert, weist ihre Fragen strikt zurück. Elisabeth findet weitere Indizien, die dafür sprechen, dass ihr Verdacht begründet ist. Sie kennt Heston House und die Gegend um St. Annes, und sie hat keine Zweifel mehr, dass es ein Geheimnis in ihrer Familie gibt, das sie noch nicht kennt.<br/><br/>Gregory hat seinem Vater unterdessen schlechte Nachrichten zu überbringen. Er ist durch die Offiziersprüfung gefallen, was Mortimer ihm sehr verübelt. Denn nach bestandener Prüfung sollte Gregory endlich seine langjährige Verlobte Rebecca heiraten.","channel":"zdf","startTime":"2017-10-07T11:45:00.000Z","endTime":"2017-10-07T13:15:00.000Z"}]}`

**Comment by cemrich** [comment]
Nice! Do you want to create a pull request?

**Comment by Medusalix** [comment]
Sure :smile:.

**Comment by Medusalix** [comment]
Sure, give me a second.
